{% set name = "pyncview" %}
{% set version = "0.99.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyncview-{{ version }}.tar.gz
  sha256: 53df16bf791b40be29909ef9ce0d6f9dc807d9ea92f01454dd9449c2295a9373

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - multiplot = pyncview.multiplot:main
    - pyncview = pyncview.pyncview:main

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - netcdf4
    - xmlplot >=0.9.28
    - matplotlib
    - pyqt

test:
  imports:
    - pyncview
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - multiplot -h

about:
  home: https://github.com/BoldingBruggeman/pyncview
  summary: 'NetCDF viewer written in Python'
  description: |
    PyNcView is a cross-platform NetCDF viewer written in Python. 
    It provides an easy-to-use graphical user interface for the creation of
    animations and publication-quality figures. It can open multiple NetCDF
    files side-by-side and can plot expressions containing NetCDF variables
    and mathematical operators.
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
