{% set name = "pyncview" %}
{% set version = "0.99.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyncview-{{ version }}.tar.gz
  sha256: 683d75742c443d38d0d3e4044a25c65120ec2f93f31fcb475153041f17d74c1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - multiplot = pyncview.multiplot:main
    - pyncview = pyncview.pyncview:main

requirements:
  build:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - netcdf4
    - xmlplot >=0.9.28
    - matplotlib
    - pyqt

test:
  imports:
    - pyncview
  requires:
    - pip
  commands:
    - pip check
    - multiplot -h

about:
  home: https://github.com/BoldingBruggeman/pyncview
  summary: 'NetCDF viewer written in Python'
  description: |
    PyNcView is a cross-platform NetCDF viewer written in Python. 
    It provides an easy-to-use graphical user interface for the creation of
    animations and publication-quality figures. It can open multiple NetCDF
    files side-by-side and can plot expressions containing NetCDF variables
    and mathematical operators.
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
